/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as ToolsWireframeRouteImport } from './routes/tools.wireframe'
import { Route as ToolsWhatsappPrintRouteImport } from './routes/tools.whatsapp-print'
import { Route as ToolsTarefasRouteImport } from './routes/tools.tarefas'
import { Route as ToolsRoteirosRouteImport } from './routes/tools.roteiros'
import { Route as ToolsPrintViralRouteImport } from './routes/tools.print-viral'
import { Route as ToolsPostSimplesRouteImport } from './routes/tools.post-simples'
import { Route as ToolsPostNoticiaRouteImport } from './routes/tools.post-noticia'
import { Route as ToolsPostFraseRouteImport } from './routes/tools.post-frase'
import { Route as ToolsGoogleDriveRouteImport } from './routes/tools.google-drive'
import { Route as ToolsCopyTitulosVideosRouteImport } from './routes/tools.copy-titulos-videos'
import { Route as ToolsCarouselPreviewRouteImport } from './routes/tools.carousel-preview'
import { Route as ToolsCarouselCreatorIaPreviewRouteImport } from './routes/tools.carousel-creator-ia-preview'
import { Route as ToolsCarouselCreatorIaRouteImport } from './routes/tools.carousel-creator-ia'
import { Route as ToolsCarouselCreator2RouteImport } from './routes/tools.carousel-creator-2'
import { Route as ToolsCarouselCreatorRouteImport } from './routes/tools.carousel-creator'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as CarouselIdRouteImport } from './routes/carousel.$id'
import { Route as CSlugRouteImport } from './routes/c.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWireframeRoute = ToolsWireframeRouteImport.update({
  id: '/tools/wireframe',
  path: '/tools/wireframe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWhatsappPrintRoute = ToolsWhatsappPrintRouteImport.update({
  id: '/tools/whatsapp-print',
  path: '/tools/whatsapp-print',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTarefasRoute = ToolsTarefasRouteImport.update({
  id: '/tools/tarefas',
  path: '/tools/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoteirosRoute = ToolsRoteirosRouteImport.update({
  id: '/tools/roteiros',
  path: '/tools/roteiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPrintViralRoute = ToolsPrintViralRouteImport.update({
  id: '/tools/print-viral',
  path: '/tools/print-viral',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPostSimplesRoute = ToolsPostSimplesRouteImport.update({
  id: '/tools/post-simples',
  path: '/tools/post-simples',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPostNoticiaRoute = ToolsPostNoticiaRouteImport.update({
  id: '/tools/post-noticia',
  path: '/tools/post-noticia',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPostFraseRoute = ToolsPostFraseRouteImport.update({
  id: '/tools/post-frase',
  path: '/tools/post-frase',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGoogleDriveRoute = ToolsGoogleDriveRouteImport.update({
  id: '/tools/google-drive',
  path: '/tools/google-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCopyTitulosVideosRoute = ToolsCopyTitulosVideosRouteImport.update({
  id: '/tools/copy-titulos-videos',
  path: '/tools/copy-titulos-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCarouselPreviewRoute = ToolsCarouselPreviewRouteImport.update({
  id: '/tools/carousel-preview',
  path: '/tools/carousel-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCarouselCreatorIaPreviewRoute =
  ToolsCarouselCreatorIaPreviewRouteImport.update({
    id: '/tools/carousel-creator-ia-preview',
    path: '/tools/carousel-creator-ia-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCarouselCreatorIaRoute = ToolsCarouselCreatorIaRouteImport.update({
  id: '/tools/carousel-creator-ia',
  path: '/tools/carousel-creator-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCarouselCreator2Route = ToolsCarouselCreator2RouteImport.update({
  id: '/tools/carousel-creator-2',
  path: '/tools/carousel-creator-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCarouselCreatorRoute = ToolsCarouselCreatorRouteImport.update({
  id: '/tools/carousel-creator',
  path: '/tools/carousel-creator',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselIdRoute = CarouselIdRouteImport.update({
  id: '/carousel/$id',
  path: '/carousel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRoute
  '/carousel/$id': typeof CarouselIdRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/tools/carousel-creator': typeof ToolsCarouselCreatorRoute
  '/tools/carousel-creator-2': typeof ToolsCarouselCreator2Route
  '/tools/carousel-creator-ia': typeof ToolsCarouselCreatorIaRoute
  '/tools/carousel-creator-ia-preview': typeof ToolsCarouselCreatorIaPreviewRoute
  '/tools/carousel-preview': typeof ToolsCarouselPreviewRoute
  '/tools/copy-titulos-videos': typeof ToolsCopyTitulosVideosRoute
  '/tools/google-drive': typeof ToolsGoogleDriveRoute
  '/tools/post-frase': typeof ToolsPostFraseRoute
  '/tools/post-noticia': typeof ToolsPostNoticiaRoute
  '/tools/post-simples': typeof ToolsPostSimplesRoute
  '/tools/print-viral': typeof ToolsPrintViralRoute
  '/tools/roteiros': typeof ToolsRoteirosRoute
  '/tools/tarefas': typeof ToolsTarefasRoute
  '/tools/whatsapp-print': typeof ToolsWhatsappPrintRoute
  '/tools/wireframe': typeof ToolsWireframeRoute
  '/w/$slug': typeof WSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRoute
  '/carousel/$id': typeof CarouselIdRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/tools/carousel-creator': typeof ToolsCarouselCreatorRoute
  '/tools/carousel-creator-2': typeof ToolsCarouselCreator2Route
  '/tools/carousel-creator-ia': typeof ToolsCarouselCreatorIaRoute
  '/tools/carousel-creator-ia-preview': typeof ToolsCarouselCreatorIaPreviewRoute
  '/tools/carousel-preview': typeof ToolsCarouselPreviewRoute
  '/tools/copy-titulos-videos': typeof ToolsCopyTitulosVideosRoute
  '/tools/google-drive': typeof ToolsGoogleDriveRoute
  '/tools/post-frase': typeof ToolsPostFraseRoute
  '/tools/post-noticia': typeof ToolsPostNoticiaRoute
  '/tools/post-simples': typeof ToolsPostSimplesRoute
  '/tools/print-viral': typeof ToolsPrintViralRoute
  '/tools/roteiros': typeof ToolsRoteirosRoute
  '/tools/tarefas': typeof ToolsTarefasRoute
  '/tools/whatsapp-print': typeof ToolsWhatsappPrintRoute
  '/tools/wireframe': typeof ToolsWireframeRoute
  '/w/$slug': typeof WSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/c/$slug': typeof CSlugRoute
  '/carousel/$id': typeof CarouselIdRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$slug': typeof RSlugRoute
  '/tools/carousel-creator': typeof ToolsCarouselCreatorRoute
  '/tools/carousel-creator-2': typeof ToolsCarouselCreator2Route
  '/tools/carousel-creator-ia': typeof ToolsCarouselCreatorIaRoute
  '/tools/carousel-creator-ia-preview': typeof ToolsCarouselCreatorIaPreviewRoute
  '/tools/carousel-preview': typeof ToolsCarouselPreviewRoute
  '/tools/copy-titulos-videos': typeof ToolsCopyTitulosVideosRoute
  '/tools/google-drive': typeof ToolsGoogleDriveRoute
  '/tools/post-frase': typeof ToolsPostFraseRoute
  '/tools/post-noticia': typeof ToolsPostNoticiaRoute
  '/tools/post-simples': typeof ToolsPostSimplesRoute
  '/tools/print-viral': typeof ToolsPrintViralRoute
  '/tools/roteiros': typeof ToolsRoteirosRoute
  '/tools/tarefas': typeof ToolsTarefasRoute
  '/tools/whatsapp-print': typeof ToolsWhatsappPrintRoute
  '/tools/wireframe': typeof ToolsWireframeRoute
  '/w/$slug': typeof WSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/c/$slug'
    | '/carousel/$id'
    | '/p/$slug'
    | '/r/$slug'
    | '/tools/carousel-creator'
    | '/tools/carousel-creator-2'
    | '/tools/carousel-creator-ia'
    | '/tools/carousel-creator-ia-preview'
    | '/tools/carousel-preview'
    | '/tools/copy-titulos-videos'
    | '/tools/google-drive'
    | '/tools/post-frase'
    | '/tools/post-noticia'
    | '/tools/post-simples'
    | '/tools/print-viral'
    | '/tools/roteiros'
    | '/tools/tarefas'
    | '/tools/whatsapp-print'
    | '/tools/wireframe'
    | '/w/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/c/$slug'
    | '/carousel/$id'
    | '/p/$slug'
    | '/r/$slug'
    | '/tools/carousel-creator'
    | '/tools/carousel-creator-2'
    | '/tools/carousel-creator-ia'
    | '/tools/carousel-creator-ia-preview'
    | '/tools/carousel-preview'
    | '/tools/copy-titulos-videos'
    | '/tools/google-drive'
    | '/tools/post-frase'
    | '/tools/post-noticia'
    | '/tools/post-simples'
    | '/tools/print-viral'
    | '/tools/roteiros'
    | '/tools/tarefas'
    | '/tools/whatsapp-print'
    | '/tools/wireframe'
    | '/w/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/c/$slug'
    | '/carousel/$id'
    | '/p/$slug'
    | '/r/$slug'
    | '/tools/carousel-creator'
    | '/tools/carousel-creator-2'
    | '/tools/carousel-creator-ia'
    | '/tools/carousel-creator-ia-preview'
    | '/tools/carousel-preview'
    | '/tools/copy-titulos-videos'
    | '/tools/google-drive'
    | '/tools/post-frase'
    | '/tools/post-noticia'
    | '/tools/post-simples'
    | '/tools/print-viral'
    | '/tools/roteiros'
    | '/tools/tarefas'
    | '/tools/whatsapp-print'
    | '/tools/wireframe'
    | '/w/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CSlugRoute: typeof CSlugRoute
  CarouselIdRoute: typeof CarouselIdRoute
  PSlugRoute: typeof PSlugRoute
  RSlugRoute: typeof RSlugRoute
  ToolsCarouselCreatorRoute: typeof ToolsCarouselCreatorRoute
  ToolsCarouselCreator2Route: typeof ToolsCarouselCreator2Route
  ToolsCarouselCreatorIaRoute: typeof ToolsCarouselCreatorIaRoute
  ToolsCarouselCreatorIaPreviewRoute: typeof ToolsCarouselCreatorIaPreviewRoute
  ToolsCarouselPreviewRoute: typeof ToolsCarouselPreviewRoute
  ToolsCopyTitulosVideosRoute: typeof ToolsCopyTitulosVideosRoute
  ToolsGoogleDriveRoute: typeof ToolsGoogleDriveRoute
  ToolsPostFraseRoute: typeof ToolsPostFraseRoute
  ToolsPostNoticiaRoute: typeof ToolsPostNoticiaRoute
  ToolsPostSimplesRoute: typeof ToolsPostSimplesRoute
  ToolsPrintViralRoute: typeof ToolsPrintViralRoute
  ToolsRoteirosRoute: typeof ToolsRoteirosRoute
  ToolsTarefasRoute: typeof ToolsTarefasRoute
  ToolsWhatsappPrintRoute: typeof ToolsWhatsappPrintRoute
  ToolsWireframeRoute: typeof ToolsWireframeRoute
  WSlugRoute: typeof WSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/wireframe': {
      id: '/tools/wireframe'
      path: '/tools/wireframe'
      fullPath: '/tools/wireframe'
      preLoaderRoute: typeof ToolsWireframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/whatsapp-print': {
      id: '/tools/whatsapp-print'
      path: '/tools/whatsapp-print'
      fullPath: '/tools/whatsapp-print'
      preLoaderRoute: typeof ToolsWhatsappPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tarefas': {
      id: '/tools/tarefas'
      path: '/tools/tarefas'
      fullPath: '/tools/tarefas'
      preLoaderRoute: typeof ToolsTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/roteiros': {
      id: '/tools/roteiros'
      path: '/tools/roteiros'
      fullPath: '/tools/roteiros'
      preLoaderRoute: typeof ToolsRoteirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/print-viral': {
      id: '/tools/print-viral'
      path: '/tools/print-viral'
      fullPath: '/tools/print-viral'
      preLoaderRoute: typeof ToolsPrintViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/post-simples': {
      id: '/tools/post-simples'
      path: '/tools/post-simples'
      fullPath: '/tools/post-simples'
      preLoaderRoute: typeof ToolsPostSimplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/post-noticia': {
      id: '/tools/post-noticia'
      path: '/tools/post-noticia'
      fullPath: '/tools/post-noticia'
      preLoaderRoute: typeof ToolsPostNoticiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/post-frase': {
      id: '/tools/post-frase'
      path: '/tools/post-frase'
      fullPath: '/tools/post-frase'
      preLoaderRoute: typeof ToolsPostFraseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/google-drive': {
      id: '/tools/google-drive'
      path: '/tools/google-drive'
      fullPath: '/tools/google-drive'
      preLoaderRoute: typeof ToolsGoogleDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/copy-titulos-videos': {
      id: '/tools/copy-titulos-videos'
      path: '/tools/copy-titulos-videos'
      fullPath: '/tools/copy-titulos-videos'
      preLoaderRoute: typeof ToolsCopyTitulosVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/carousel-preview': {
      id: '/tools/carousel-preview'
      path: '/tools/carousel-preview'
      fullPath: '/tools/carousel-preview'
      preLoaderRoute: typeof ToolsCarouselPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/carousel-creator-ia-preview': {
      id: '/tools/carousel-creator-ia-preview'
      path: '/tools/carousel-creator-ia-preview'
      fullPath: '/tools/carousel-creator-ia-preview'
      preLoaderRoute: typeof ToolsCarouselCreatorIaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/carousel-creator-ia': {
      id: '/tools/carousel-creator-ia'
      path: '/tools/carousel-creator-ia'
      fullPath: '/tools/carousel-creator-ia'
      preLoaderRoute: typeof ToolsCarouselCreatorIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/carousel-creator-2': {
      id: '/tools/carousel-creator-2'
      path: '/tools/carousel-creator-2'
      fullPath: '/tools/carousel-creator-2'
      preLoaderRoute: typeof ToolsCarouselCreator2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/carousel-creator': {
      id: '/tools/carousel-creator'
      path: '/tools/carousel-creator'
      fullPath: '/tools/carousel-creator'
      preLoaderRoute: typeof ToolsCarouselCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousel/$id': {
      id: '/carousel/$id'
      path: '/carousel/$id'
      fullPath: '/carousel/$id'
      preLoaderRoute: typeof CarouselIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CSlugRoute: CSlugRoute,
  CarouselIdRoute: CarouselIdRoute,
  PSlugRoute: PSlugRoute,
  RSlugRoute: RSlugRoute,
  ToolsCarouselCreatorRoute: ToolsCarouselCreatorRoute,
  ToolsCarouselCreator2Route: ToolsCarouselCreator2Route,
  ToolsCarouselCreatorIaRoute: ToolsCarouselCreatorIaRoute,
  ToolsCarouselCreatorIaPreviewRoute: ToolsCarouselCreatorIaPreviewRoute,
  ToolsCarouselPreviewRoute: ToolsCarouselPreviewRoute,
  ToolsCopyTitulosVideosRoute: ToolsCopyTitulosVideosRoute,
  ToolsGoogleDriveRoute: ToolsGoogleDriveRoute,
  ToolsPostFraseRoute: ToolsPostFraseRoute,
  ToolsPostNoticiaRoute: ToolsPostNoticiaRoute,
  ToolsPostSimplesRoute: ToolsPostSimplesRoute,
  ToolsPrintViralRoute: ToolsPrintViralRoute,
  ToolsRoteirosRoute: ToolsRoteirosRoute,
  ToolsTarefasRoute: ToolsTarefasRoute,
  ToolsWhatsappPrintRoute: ToolsWhatsappPrintRoute,
  ToolsWireframeRoute: ToolsWireframeRoute,
  WSlugRoute: WSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
